# Generated by Django 4.0.7 on 2023-02-20 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='donor',
            new_name='donor_details',
        ),
    ]
