# Generated by Django 4.0.7 on 2023-02-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_enroll_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll_details',
            name='dob',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='enroll_details',
            name='dod',
            field=models.CharField(max_length=255),
        ),
    ]
