# Generated by Django 4.0.7 on 2023-03-03 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0008_liv_reg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='liv_reg',
        ),
    ]
