# Generated by Django 4.0.7 on 2023-03-06 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0011_lungs_reg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lungs_reg',
        ),
    ]
