# Generated by Django 4.0.7 on 2023-03-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0014_kid_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=255)),
                ('donor_id', models.CharField(max_length=255)),
                ('organ', models.CharField(max_length=255)),
                ('disease', models.CharField(max_length=255)),
            ],
        ),
    ]
