# Generated by Django 4.0.7 on 2023-03-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0015_admin_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='eye_details',
            name='organ',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='heart_details',
            name='organ',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kid_reg',
            name='organ',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='liv_reg',
            name='organ',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lun_reg',
            name='organ',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
