# Generated by Django 4.0.7 on 2023-03-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0016_eye_details_organ_heart_details_organ_kid_reg_organ_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eye_details',
            name='disease',
            field=models.CharField(default='Pending', max_length=255, null=True),
        ),
    ]
