# Generated by Django 4.0.7 on 2023-03-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0017_eye_details_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='heart_details',
            name='disease',
            field=models.CharField(default='Pending', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kid_reg',
            name='disease',
            field=models.CharField(default='Pending', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='liv_reg',
            name='disease',
            field=models.CharField(default='Pending', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lun_reg',
            name='disease',
            field=models.CharField(default='Pending', max_length=255, null=True),
        ),
    ]
