# Generated by Django 4.0.7 on 2023-03-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0018_heart_details_disease_kid_reg_disease_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eye_details',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
