# Generated by Django 4.0.7 on 2023-03-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0019_eye_details_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='heart_details',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='kid_reg',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='liv_reg',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='lun_reg',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
