# Generated by Django 4.0.7 on 2023-03-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0021_rename_tissue_typing_liv_reg_tissue_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eye_details',
            name='consent',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='heart_details',
            name='consent',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='kid_reg',
            name='consent',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='liv_reg',
            name='consent',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='lun_reg',
            name='consent',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
