# Generated by Django 4.0.7 on 2023-03-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0022_eye_details_consent_heart_details_consent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eye_details',
            name='d_type_disease',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='heart_details',
            name='d_type_disease',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kid_reg',
            name='d_type_disease',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='liv_reg',
            name='d_type_disease',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lun_reg',
            name='d_type_disease',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
