# Generated by Django 4.0.7 on 2023-03-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0023_eye_details_d_type_disease_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eye_details',
            name='boolean',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='heart_details',
            name='boolean',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='kid_reg',
            name='boolean',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='liv_reg',
            name='boolean',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='lun_reg',
            name='boolean',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
