# Generated by Django 5.2.5 on 2025-08-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50, unique=True)),
                ('Lastname', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('role', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Employee_details',
            },
        ),
    ]
