from django.db import models

# Create your models here.
class patient_details(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    password = models.CharField(max_length=200)
    phone = models.BigIntegerField()
    address = models.CharField(max_length=255)

class patient_eye_registration(models.Model):
    full_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    iop = models.CharField(max_length=255)
    visual_acuity = models.CharField(max_length=255)
    corneal_thickness = models.CharField(max_length=255)
    corneal_topo = models.CharField(max_length=255)
    tissue_type = models.CharField(max_length=255)
    corneal_curvature = models.CharField(max_length=255)
    corneal_dia = models.CharField(max_length=255)
    endothelial = models.CharField(max_length=255)
    organ = models.CharField(default="Eye", max_length=255, null=True)
    disease = models.CharField(default="Pending", max_length=255, null=True)
    p_type_disease = models.CharField(max_length=255, null=True)
    approved = models.BooleanField(default=False, null=True)
    boolean = models.BooleanField(default=False, null=True)

class patient_heart_re(models.Model):
    full_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    ejection_fraction = models.CharField(max_length=255)
    pap = models.CharField(max_length=255)
    pvg = models.CharField(max_length=255)
    aortic_valve = models.CharField(max_length=255)
    lavi = models.CharField(max_length=255)
    lvef = models.CharField(max_length=255)
    mitral_valve_regurgitation = models.CharField(max_length=255)
    mitral_valve_stenosis = models.CharField(max_length=255)
    wall_motion = models.CharField(max_length=255)
    qt_interval = models.CharField(max_length=255)
    qrs_duration = models.CharField(max_length=255)
    atrial = models.CharField(max_length=255)
    bradycardia = models.CharField(max_length=255)
    heart_rate = models.CharField(max_length=255)
    p_wave = models.CharField(max_length=255)
    pulmonary = models.CharField(max_length=255)
    cardiac_o = models.CharField(max_length=255)
    coronary_art = models.CharField(max_length=255)
    coronary_ani = models.CharField(max_length=255)
    mild_stenosis = models.CharField(max_length=255)
    moderate_stenosis = models.CharField(max_length=255)
    ffr = models.CharField(max_length=255)
    stenosis = models.CharField(max_length=255)
    heart_size = models.CharField(max_length=255)
    hemo = models.CharField(max_length=255)
    blood_type = models.CharField(max_length=255)
    tissue_type = models.CharField(max_length=255)
    organ = models.CharField(default="Heart", max_length=255, null=True)
    disease = models.CharField(default="Pending", max_length=255, null=True)
    p_type_disease = models.CharField(max_length=255, null=True)
    approved = models.BooleanField(default=False, null=True)
    boolean = models.BooleanField(default=False, null=True)



class patient_liver_re(models.Model):
    full_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    aspartate = models.CharField(max_length=255)
    alanine = models.CharField(max_length=255)
    bilirubin = models.CharField(max_length=255)
    platelets = models.CharField(max_length=255)
    alkaline = models.CharField(max_length=255)
    albumin = models.CharField(max_length=255)
    hepatitis = models.CharField(max_length=255)
    afp = models.CharField(max_length=255)
    liver_biopsy = models.CharField(max_length=255)
    imaging_test = models.CharField(max_length=255)
    CDT = models.CharField(max_length=255)
    EtG = models.CharField(max_length=255)
    PEth = models.CharField(max_length=255)
    blood_type = models.CharField(max_length=255)
    tissue_type = models.CharField(max_length=255)
    cross_test = models.CharField(max_length=255)
    viral_test = models.CharField(max_length=255)
    organ = models.CharField(default="Liver", max_length=255, null=True)
    disease = models.CharField(default="Pending", max_length=255, null=True)
    p_type_disease = models.CharField(max_length=255, null=True)
    approved = models.BooleanField(default=False, null=True)
    boolean = models.BooleanField(default=False, null=True)

class patient_lungs_re(models.Model):
    full_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    fev = models.CharField(max_length=255)
    chest_x_ray = models.CharField(max_length=255)
    pef = models.CharField(max_length=255)
    bpt = models.CharField(max_length=255)
    blood_test = models.CharField(max_length=255)
    tumor_size = models.CharField(max_length=255)
    sputum_culture = models.CharField(max_length=255)
    tst = models.CharField(max_length=255)
    igras = models.CharField(max_length=255)
    ct_scan = models.CharField(max_length=255)
    mri_scan = models.CharField(max_length=255)
    pet_scan = models.CharField(max_length=255)
    blood_type = models.CharField(max_length=255)
    tissue_type = models.CharField(max_length=255)
    crossmatch = models.CharField(max_length=255)
    viral_test = models.CharField(max_length=255)
    organ = models.CharField(default="Lungs", max_length=255, null=True)
    disease = models.CharField(default="Pending", max_length=255, null=True)
    p_type_disease = models.CharField(max_length=255, null=True)
    approved = models.BooleanField(default=False, null=True)
    boolean = models.BooleanField(default=False, null=True)

class patient_kidney_re(models.Model):
    full_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    creatinine = models.CharField(max_length=255)
    bun = models.CharField(max_length=255)
    urine_albumin = models.CharField(max_length=255)
    urine_protien = models.CharField(max_length=255)
    serum_creatinine = models.CharField(max_length=255)
    urine_output = models.CharField(max_length=255)
    urinalysis = models.CharField(max_length=255)
    rbc = models.CharField(max_length=255)
    kidney_biopsy = models.CharField(max_length=255)
    immunological = models.CharField(max_length=255)
    blood_type = models.CharField(max_length=255)
    tissue_type = models.CharField(max_length=255)
    cross_test = models.CharField(max_length=255)
    imaging = models.CharField(max_length=255)
    viral_test = models.CharField(max_length=255)
    organ = models.CharField(default="Kidney", max_length=255, null=True)
    disease = models.CharField(default="Pending", max_length=255, null=True)
    p_type_disease = models.CharField(max_length=255, null=True)
    approved = models.BooleanField(default=False, null=True)
    boolean = models.BooleanField(default=False, null=True)

class admin_patient(models.Model):
    full_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    organ = models.CharField(max_length=255)
    disease_status = models.CharField(max_length=255)





