# Generated by Django 4.0.7 on 2023-03-07 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patient_heart_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patient_heart_registration',
        ),
    ]
