# Generated by Django 4.0.7 on 2023-03-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_patient_heart_re'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient_liver_re',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('aspartate', models.CharField(max_length=255)),
                ('alanine', models.CharField(max_length=255)),
                ('bilirubin', models.CharField(max_length=255)),
                ('platelets', models.CharField(max_length=255)),
                ('alkaline', models.CharField(max_length=255)),
                ('albumin', models.CharField(max_length=255)),
                ('hepatitis', models.CharField(max_length=255)),
                ('afp', models.CharField(max_length=255)),
                ('liver_biopsy', models.CharField(max_length=255)),
                ('imaging_test', models.CharField(max_length=255)),
                ('CDT', models.CharField(max_length=255)),
                ('EtG', models.CharField(max_length=255)),
                ('PEth', models.CharField(max_length=255)),
                ('blood_type', models.CharField(max_length=255)),
                ('tissue_typing', models.CharField(max_length=255)),
                ('cross_test', models.CharField(max_length=255)),
                ('viral_test', models.CharField(max_length=255)),
            ],
        ),
    ]
