# Generated by Django 4.0.7 on 2023-03-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_patient_liver_re'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient_lungs_re',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('fev', models.CharField(max_length=255)),
                ('chest_x_ray', models.CharField(max_length=255)),
                ('pef', models.CharField(max_length=255)),
                ('bpt', models.CharField(max_length=255)),
                ('blood_test', models.CharField(max_length=255)),
                ('tumor_size', models.CharField(max_length=255)),
                ('sputum_culture', models.CharField(max_length=255)),
                ('tst', models.CharField(max_length=255)),
                ('igras', models.CharField(max_length=255)),
                ('ct_scan', models.CharField(max_length=255)),
                ('mri_scan', models.CharField(max_length=255)),
                ('pet_scan', models.CharField(max_length=255)),
                ('blood_type', models.CharField(max_length=255)),
                ('tissue_typing', models.CharField(max_length=255)),
                ('crossmatch', models.CharField(max_length=255)),
                ('viral_test', models.CharField(max_length=255)),
            ],
        ),
    ]
