# Generated by Django 4.0.7 on 2023-03-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_patient_kidney_re'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('organ', models.CharField(max_length=255)),
                ('disease_status', models.CharField(max_length=255)),
            ],
        ),
    ]
