# Generated by Django 4.0.7 on 2023-03-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_admin_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_eye_registration',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='patient_eye_registration',
            name='disease',
            field=models.CharField(default='Pending', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient_eye_registration',
            name='organ',
            field=models.CharField(default='Eye', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient_heart_re',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='patient_heart_re',
            name='disease',
            field=models.CharField(default='Pending', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient_heart_re',
            name='organ',
            field=models.CharField(default='Heart', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient_kidney_re',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='patient_kidney_re',
            name='disease',
            field=models.CharField(default='Pending', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient_kidney_re',
            name='organ',
            field=models.CharField(default='Kidney', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient_liver_re',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='patient_liver_re',
            name='disease',
            field=models.CharField(default='Pending', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient_liver_re',
            name='organ',
            field=models.CharField(default='Liver', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient_lungs_re',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='patient_lungs_re',
            name='disease',
            field=models.CharField(default='Pending', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient_lungs_re',
            name='organ',
            field=models.CharField(default='Lungs', max_length=255, null=True),
        ),
    ]
