# Generated by Django 4.0.7 on 2023-03-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_rename_tissue_typing_patient_liver_re_tissue_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_eye_registration',
            name='p_type_disease',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient_heart_re',
            name='p_type_disease',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient_kidney_re',
            name='p_type_disease',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient_liver_re',
            name='p_type_disease',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient_lungs_re',
            name='p_type_disease',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
