# Generated by Django 4.0.7 on 2023-03-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_patient_eye_registration_p_type_disease_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_eye_registration',
            name='boolean',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='patient_heart_re',
            name='boolean',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='patient_kidney_re',
            name='boolean',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='patient_liver_re',
            name='boolean',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='patient_lungs_re',
            name='boolean',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
