from datetime import datetime

from django.db import models

# Create your models here.
class donor_details(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    password = models.CharField(max_length=200)
    phone = models.BigIntegerField()
    address = models.CharField(max_length=255)

class enroll_details(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    gender = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    dob = models.CharField(max_length=255)
    dod = models.CharField(max_length=255)
    height = models.CharField(max_length=255)
    weight = models.CharField(max_length=255)
    martial_status = models.CharField(max_length=255)
    cause_of_death = models.CharField(max_length=255)
    address = models.CharField(max_length=255)


class organ_details(models.Model):
    name = models.CharField(max_length=255)
    age = models.BigIntegerField()
    email = models.CharField(max_length=255)
    phone = models.BigIntegerField()
    gender = models.CharField(max_length=255)
    aadhaar_no = models.BigIntegerField()
    cause_of_death = models.CharField(max_length=255)
    blood = models.CharField(max_length=255)
    organ_name = models.CharField(max_length=255)
    f_consent = models.CharField(max_length=255)
    dod = models.DateField()
    medical_conditions =models.CharField(max_length=255)
    general_appearance = models.CharField(max_length=255)
    cardi_exam = models.CharField(max_length=255)
    respiratory_health = models.CharField(max_length=255)
    liver_function = models.CharField(max_length=255)
    renal_function = models.CharField(max_length=255)
    drug_usage = models.CharField(max_length=255)
    organ_function = models.CharField(max_length=255)
    cold_ischemia = models.CharField(max_length=255)
    ecg = models.CharField(max_length=255)
    biopsy = models.CharField(max_length=255)
    imaging_test = models.CharField(max_length=255)
    visual_acuity = models.CharField(max_length=255)

class eye_details(models.Model):
    donor_name = models.CharField(max_length=255)
    donor_id = models.CharField(max_length=255)
    tonometry = models.CharField(max_length=255)
    slit_lamp = models.CharField(max_length=255)
    pachymetry = models.CharField(max_length=255)
    serological_testing = models.CharField(max_length=255)
    culture = models.CharField(max_length=255)
    microscopy = models.CharField(max_length=255)
    tissue_type = models.CharField(max_length=255)
    hla = models.CharField(max_length=255)
    corneal_mes = models.CharField(max_length=255)
    corneal_curv = models.CharField(max_length=255)
    corneal_topo = models.CharField(max_length=255)
    corneal_dia = models.CharField(max_length=255)
    endothelial_cell = models.CharField(max_length=255)
    organ = models.CharField(max_length=255, null=True)
    disease = models.CharField(default="Pending", max_length=255, null=True)
    d_type_disease = models.CharField(max_length=255, null=True)
    approved = models.BooleanField(default=False,null=True)
    consent = models.BooleanField(default=False, null=True)
    boolean = models.BooleanField(default=False, null=True)

class heart_details(models.Model):
    donor_name = models.CharField(max_length=255)
    donor_id = models.CharField(max_length=255)
    ejection_fraction = models.CharField(max_length=255)
    pap= models.CharField(max_length=255)
    pvg= models.CharField(max_length=255)
    aortic_valve= models.CharField(max_length=255)
    lavi= models.CharField(max_length=255)
    lvef= models.CharField(max_length=255)
    mitral_valve_regurgitation= models.CharField(max_length=255)
    mitral_valve_stenosis= models.CharField(max_length=255)
    wall_motion= models.CharField(max_length=255)
    qt_interval= models.CharField(max_length=255)
    qrs_duration= models.CharField(max_length=255)
    atrial= models.CharField(max_length=255)
    bradycardia= models.CharField(max_length=255)
    heart_rate= models.CharField(max_length=255)
    p_wave= models.CharField(max_length=255)
    pulmonary= models.CharField(max_length=255)
    cardiac_o= models.CharField(max_length=255)
    coronary_art= models.CharField(max_length=255)
    coronary_ani= models.CharField(max_length=255)
    mild_stenosis= models.CharField(max_length=255)
    moderate_stenosis= models.CharField(max_length=255)
    ffr= models.CharField(max_length=255)
    stenosis= models.CharField(max_length=255)
    heart_size= models.CharField(max_length=255)
    hemo= models.CharField(max_length=255)
    blood_type= models.CharField(max_length=255)
    tissue_type= models.CharField(max_length=255)
    organ = models.CharField(max_length=255, null=True)
    disease = models.CharField(default="Pending", max_length=255, null=True)
    approved = models.BooleanField(default=False, null=True)
    d_type_disease = models.CharField(max_length=255, null=True)
    consent = models.BooleanField(default=False, null=True)
    boolean = models.BooleanField(default=False, null=True)


class liv_reg(models.Model):
    donor_name = models.CharField(max_length=255)
    donor_id = models.CharField(max_length=255)
    aspartate = models.CharField(max_length=255)
    alanine = models.CharField(max_length=255)
    bilirubin = models.CharField(max_length=255)
    platelets = models.CharField(max_length=255)
    alkaline = models.CharField(max_length=255)
    albumin = models.CharField(max_length=255)
    hepatitis = models.CharField(max_length=255)
    afp = models.CharField(max_length=255)
    liver_biopsy = models.CharField(max_length=255)
    imaging_test = models.CharField(max_length=255)
    CDT = models.CharField(max_length=255)
    EtG = models.CharField(max_length=255)
    PEth = models.CharField(max_length=255)
    blood_type = models.CharField(max_length=255)
    tissue_type = models.CharField(max_length=255)
    cross_test = models.CharField(max_length=255)
    viral_test = models.CharField(max_length=255)
    organ = models.CharField(max_length=255, null=True)
    disease = models.CharField(default="Pending", max_length=255, null=True)
    approved = models.BooleanField(default=False, null=True)
    d_type_disease = models.CharField(max_length=255, null=True)
    consent = models.BooleanField(default=False, null=True)
    boolean = models.BooleanField(default=False, null=True)


class lun_reg(models.Model):
    donor_name = models.CharField(max_length=255)
    donor_id = models.CharField(max_length=255)
    fev = models.CharField(max_length=255)
    chest_x_ray = models.CharField(max_length=255)
    pef = models.CharField(max_length=255)
    bpt = models.CharField(max_length=255)
    blood_test = models.CharField(max_length=255)
    tumor_size = models.CharField(max_length=255)
    sputum_culture = models.CharField(max_length=255)
    tst = models.CharField(max_length=255)
    igras = models.CharField(max_length=255)
    ct_scan = models.CharField(max_length=255)
    mri_scan = models.CharField(max_length=255)
    pet_scan = models.CharField(max_length=255)
    blood_type = models.CharField(max_length=255)
    tissue_type = models.CharField(max_length=255)
    crossmatch = models.CharField(max_length=255)
    viral_test = models.CharField(max_length=255)
    organ = models.CharField(max_length=255, null=True)
    disease = models.CharField(default="Pending", max_length=255, null=True)
    approved = models.BooleanField(default=False, null=True)
    d_type_disease = models.CharField(max_length=255, null=True)
    consent = models.BooleanField(default=False, null=True)
    boolean = models.BooleanField(default=False, null=True)


class kid_reg(models.Model):
    donor_name = models.CharField(max_length=255)
    donor_id = models.CharField(max_length=255)
    creatinine = models.CharField(max_length=255)
    bun = models.CharField(max_length=255)
    urine_albumin = models.CharField(max_length=255)
    urine_protien = models.CharField(max_length=255)
    serum_creatinine = models.CharField(max_length=255)
    urine_output = models.CharField(max_length=255)
    urinalysis = models.CharField(max_length=255)
    rbc = models.CharField(max_length=255)
    kidney_biopsy = models.CharField(max_length=255)
    immunological = models.CharField(max_length=255)
    blood_type = models.CharField(max_length=255)
    tissue_type = models.CharField(max_length=255)
    cross_test = models.CharField(max_length=255)
    imaging = models.CharField(max_length=255)
    viral_test = models.CharField(max_length=255)
    organ = models.CharField(max_length=255, null=True)
    disease = models.CharField(default="Pending", max_length=255, null=True)
    approved = models.BooleanField(default=False, null=True)
    d_type_disease = models.CharField(max_length=255, null=True)
    consent = models.BooleanField(default=False, null=True)
    boolean = models.BooleanField(default=False, null=True)


class admin_donor(models.Model):
    donor_name = models.CharField(max_length=255)
    donor_id = models.CharField(max_length=255)
    organ = models.CharField(max_length=255)
    disease = models.CharField(max_length=255)


